### PR TITLE
add option to fail on I/O errors

### PR DESCRIPTION
**Pull request by fho**
This commit introduces an Option for Glob(), GlobWalk() and FilepathGlob() to handle encountered I/O errors as fatal. When the option is enabled and an I/O error happens, globbing is aborted and the error is returned.
By default the globbing function continue when an I/O error happens and only skip the related file an directory. This is the same behaviour as before.

The new option is useful when the user should be notified about broken symlinks, non-existing paths in the pattern or general I/O errors that were encountered.

An Opt type is introduced that follows the Option pattern. Opt is returned by the WithFailOnIOErrors() function. The exported functions are changed to accept as last argument a variadic ...Opt argument.
When the functions are called, they instantiate a glob type instance, that stores the value of the option in an failOnIOErrors field. All functions that do I/O operations are converted to being methods of glob, to be able to access failOnIOErrors.
If an I/O operation encounters an error and failOnIOErrors is set, the error is returned.
If failOnIOErrors is not set, the functions behave the same as before.

The introduced Opt type and glob struct allow to extend the package with further options, without having to break the API in the future.

Testcases were added for Glob and GlobWalk to check if WithFailOnIOErrors causes these functions to abort and return an error.

The code could be refactored in a follow-up to use the new glob type to store the arguments that are currently passed around on functions calls like fsys and pattern.

------------

Please let me know if you are interested in general to add this functionality and if there is something to improve.

I plan to replace the existing doublestar implementation in https://github.com/simplesurance/baur with yours and require for that the functionality of this PR.

### CODE REVIEW

**Comment by bmatcuk** [comment]
@fho thanks for the PR! Sorry it's taken me a while to go over it! Looks awesome to me - I really appreciate that you were careful to not change the public-facing API so that it would be compatible with existing users. Nice!

I'm going to merge right now and then I have another commit with some small changes (to the private-side implementation, so I _think_ baur should still work without any changes on your end) that I'll push into the repo after that. Then I'll cut the release - should be 10 minutes or so, as long as I don't run into any trouble 😆 

Thanks again!

**Comment by fho** [comment]
@bmatcuk great, thanks a lot for merging it! I'm happy that you also find it useful! :tada: :-)

**Comment by twpayne** [comment]
This incorrectly returns errors when files don't exist. See #73.

**Comment by fho** [comment]
@twpayne that is the expected behavior.

quote from the description of this PR:

> The new option is useful when the user should be notified about broken symlinks, non-existing paths in the pattern or general I/O errors that were encountered.

**Pull request merged**
