### PR TITLE
Allow basedir to be specified when calling Glob

### PR DESCRIPTION
**Pull request by SPARTAN563**
The current glob implementation works well for most situations, however there are instances where the application's current directory doesn't represent the root at which you would like to start globbing, and manually building up a glob expression which includes the directory can be problematic.

This PR solves the issue by requiring the consumer to provide the base directory they wish to perform the glob relative to - it will be used if the glob expression is determined to be relative, falling back on using the root ('/' or '\\') if an absolute path is specified in the glob expression.

This change was necessary to support our use case in [GitLab CI's build runner](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner) in conjunction with [Thargo](https://github.com/EMSSConsulting/Thargo).

### CODE REVIEW

**Comment by bmatcuk** [comment]
It's an interesting idea, I have some issues with it:

* Your commits changed indentation, which makes it hard to see what actually changed since nearly every line is marked as changed. Maybe tabs are the more standard "go" way of doing things; that could be my bad. But I can't accept a pull request that changes every line of code because I don't have the time to make sure all those changes are ok.
* You changed the signature of Glob, which means your pull request will break any existing code using doublestar. I could increase the major version to signal the breaking change, but...
* Glob can already take an absolute path... rather than passing a base path and a relative path, just join those together outside of Glob and pass the absolute path to Glob. Go's [filepath](https://golang.org/pkg/path/filepath/) library, particularly [Join](https://golang.org/pkg/path/filepath/#Join) can be used to build your absolute path before calling Glob. The documentation isn't clear on this, so I'll update that now.

**Comment by SPARTAN563** [comment]
Hi @bmatcuk,
Sorry about the indentation issue, just recently came to my attention that my editor probably isn't running `go fmt` for some reason - looking into addressing that and then I'll update this PR.

Understood RE the major version issue, really looking forward to a good Go solution to that but just not there yet. I'm not adverse to changing the signature to something like `GlobFrom(basedir, pattern string)` - which coincidentally probably makes more sense. The only problem I have regarding using `filepath.Join` is that it then requires you to write your glob expressions in a platform specific way (i.e. `a/b**` will not work on Windows) - and asking users to go one step further and apply `filepath.FromSlash` to their expressions beforehand seems a bit excessive. What I am really looking for there is to have `Glob` behave the same way that `Match` does, and `PathGlob` behave the same way `PathMatch` does - which significantly simplifies the conceptual model - of course that does change the way `Glob` behaves, which is again, a breaking change.

Let me clean up the PR quickly so you have some insight into what has changed, I'm pretty happy at the moment simply having an implementation which offers what this does now, so worst case scenario I just stick with importing our fork.

**Comment by bmatcuk** [comment]
Seems perfectly reasonable to me:

```go
matches := doublestar.Glob(filepath.Join(basedir, filepath.FromSlash("my/pattern")))
```

Globs are inherently platform specific because you're asking the filesystem for information. That's why the official standard library's implementation of Glob, and doublestar's implementation by extension, assume that the pattern will be formatted for the platform. Having a version that assumes `/` as the separator doesn't really make sense.

doublestar was written to be a drop-in replacement for path.Match, filepath.Match, and filepath.Glob. I think adding some "convenience" functions to help format paths appropriately is beyond the scope of this library, especially when it is already implemented by the filepath package.

Sorry.

**Comment by SPARTAN563** [comment]
All good, quite happy to maintain a fork with the functionality we're looking for.

A recommendation though, perhaps consider running `go fmt` on your codebase, it'll vastly simplify the process of accepting PRs from other people in future :wink:

**Pull request closed without merging**
