### PR TITLE
gofmt -s

### PR DESCRIPTION
**Pull request by shawnps**

### CODE REVIEW

**Comment by bmatcuk** [comment]
Convince me that this is necessary...

**Comment by shawnps** [comment]
@bmatcuk I can try but obviously you can do whatever you want.

3 years ago the Go team did a survey of Go packages in the wild and 70% of them were formatted according to gofmt's rules (https://blog.golang.org/go-fmt-your-code).

I run [Go Report Card](http://goreportcard.com/) and I'd say almost every popular package that goes through it is gofmted already. It's prominent in the Go community and most editors have plugins to automatically gofmt your code.

I'd love to hear your reasons for why you aren't using it just for my own curiosity.

**Comment by bmatcuk** [comment]
I don't like using tabs for indents. They cause a lot of line wrapping or horizontal scrolling. If I have an "if" inside a loop inside a function, I'm already half way across the screen with tabs. They also make code harder to scan because my eyes have to move further.

Yes, you can configure _some_ editors to display tabs with smaller tab stops; say, 2 spaces. But then why don't we just use 2 spaces and call it a day? They'll display the same way on everyone's screen regardless of what editor they're using and what settings they may or may not have altered. Spaces are more consistent and unambiguous.

Additionally, why should I alter my style for go? No other language has the audacity to prescribe a coding style. Not even python, with it's enforced indent rules, requires a specific style of indent. I've settled on my preferences after nearly 25 years of coding and, while I'm open to making adjustments, I'm not going to change because someone decided they were going to force their preferences on me. If you can _convince_ me of the merits of your way, I'll assimilate that which makes me better. But I'm not convinced.

The argument of uniformity is bogus... every other language is doing just fine without any hard fast rules about style. Within a project, sure, uniform style is good. But the language as a whole? Do whatever gives you the warm fuzzies.

My two cents.

**Comment by shawnps** [comment]
@bmatcuk thanks for the response. 

I used to write a lot of Python as well, and I'd find it tedious to read the source of external libs because there were so many ways to format it and not everyone used the same PEP8 rules (or used PEP8 at all). 

I'm also unsure how enforcing 2 spaces would be any different. What if I hate spaces and love tabs?

I think it's harsh to imply that I tried to force preferences on you. I made a pull request which is a pretty basic feature of GitHub to a repo you own, and you said no, and I closed the PR. Also I've worked with people who have cited their XX years of experience as a way to shut down the discussion, and they are miserable people to work with.

The only argument I can make is that by not using gofmt, you make it more difficult for a large majority of Golang users to read and contribute to your code. Which is fine if that's nothing something you care about. 

I didn't make this PR with any sort of malicious intent. Please know you're in the minority here and there are some people (like me) who explicitly won't use import anything you write if it's not run through gofmt, because it's considered a basic requirement. Like I said if you don't care that's fine, maybe GitHub is just a free backup for your code.

**Pull request closed without merging**
